import { Inter } from '@next/font/google';
import Head from 'next/head';
import Link from 'next/link';
import styles from '../styles/Home.module.css';

const inter = Inter({ subsets: ['latin'] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Explore Next JS</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <header>
        <nav>
          <div>Logo</div>
          <Link href='/'>Home</Link>
          <Link href='/events'>Events</Link>
          <Link href='/about-us'>About</Link>
        </nav>
      </header>

      <main className={styles.main}>
        <Link href=''>
          <h2>Events In London</h2>
          <p>
            Lorem ipsum dolor sit amet consectetur, adipisicing elit. Aliquid quo doloribus earum ea, aliquam, labore
            architecto beatae at quidem provident corrupti ducimus iusto hic consequatur?
          </p>
        </Link>
        <Link href=''>
          <h2>Events In San Francisco</h2>
          <p>
            Lorem ipsum dolor sit amet consectetur, adipisicing elit. Aliquid quo doloribus earum ea, aliquam, labore
            architecto beatae at quidem provident corrupti ducimus iusto hic consequatur?
          </p>
        </Link>
        <Link href=''>
          <h2>Events In Barcelona</h2>
          <p>
            Lorem ipsum dolor sit amet consectetur, adipisicing elit. Aliquid quo doloribus earum ea, aliquam, labore
            architecto beatae at quidem provident corrupti ducimus iusto hic consequatur?
          </p>
        </Link>
      </main>
    </>
  );
}
